### ISSUE TITLE
Wait on subscriptions

### ISSUE THREAD

**Issue by virgotopia** [xolvio/meteor-inspectlet#1]
Hello,
Thank you for the package.

Any chance to put in the docs an example how to deal with subscriptions ( the screenshot is taken before the template have data to display, even with fast-rendered package) and the Inspectlet's "Change Page URL" (http://www.inspectlet.com/docs#change_page_url) ?

**Comment by SamHatoum** [comment]
I just made a change to the routing. Could you see if that helped? Version 1.0.1

**Comment by SamHatoum** [comment]
Hey if this is not fixed, please reopen

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.

**Comment by virgotopia** [comment]
Your patch fix the "wait on subscription" issue, thank you.
