### ISSUE TITLE
Integration for Mobile?

### ISSUE THREAD

**Issue by kartikTT** [xolvio/meteor-inspectlet#5]
Any ideas on whether this could be integrated for iOS/Android apps being built with Meteor? I've tried adding the package, but sessions are only recorded from my browser - not the app.

**Comment by ghost** [comment]
I don't know. I would suggest that you look in the Inspectlet documentation and/or ask the Inspectlet support if it is supported. Also have a look if Inspectlet is loaded in the app at all via Chrome Dev Tools.

**Comment by kartikTT** [comment]
Thanks @Sanjo, I reached out to Inspectlet and they confirmed that it is not supported for mobile apps.
